# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1349078274);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1349078394);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1349136831);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 604160);
user_pref("browser.download.lastDir", "/home/tiffanyphan/Desktop");
user_pref("browser.migration.version", 6);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.buildID", "20120713224749");
user_pref("browser.startup.homepage_override.mstone", "14.0.1");
user_pref("browser.syncPromoViewsLeft", 0);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountTotal", 6);
user_pref("extensions.blocklist.pingCountVersion", 6);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 12);
user_pref("extensions.enabledAddons", "globalmenu@ubuntu.com:3.2.5,ubufox@ubuntu.com:2.1.1,{972ce4c6-7e08-4474-a285-3208198ce6fd}:14.0.1");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1345241840000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1345241804000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox/extensions/globalmenu@ubuntu.com\",\"mtime\":1345241804000}}}]");
user_pref("extensions.lastAppVersion", "14.0.1");
user_pref("extensions.lastPlatformVersion", "14.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("idle.lastDailyNotification", 1347860138);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1347860139);
user_pref("places.history.expiration.transient_current_max_pages", 77239);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.warn_viewing_mixed", false);
user_pref("spellchecker.dictionary", "en_US");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1347860139);
user_pref("toolkit.startup.last_success", 1349136710);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1350353384);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
